language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm config set spin false
  - npm install -g yarn
  - npm install -g npm@^5
script:
  - yarn test-ci
  - yarn build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "g7kty/Bjv6F+65qIBy5D2bhD0jIJYU7a7NR1EQebR6VJ7meNhOkc3MIwIiYH7ycMOlULJGwr2NyIoR81TlUzWdA1pWxytW/t8uzUygZSWjTDtn+yt2S25pG39SFGPdGD7nvsUkt+14rvVVieIsk+z7FY5Y5XSMW8awU0V7I9pWs61Oc5JzjuvtqqJwHAeBiHQgpX5QIe6LI8k7+ke/N7/iv2qo7QkB9Z4A1QDWNNIiXOmbDD+XKzYkdYdRSUnJiigk5ykTSHmVbxTZc6MEutJajL19iij9DVnS8sNuqKy0iNGvvSS75CWv6gltJHc+YNGIuZzKO/40ioaMLapYej62aMsEp+UpIDHPZ9uEJuCIWYLZxhYV85knigwDBO2qc76Frj/cmXbKDNeP4/k877qpPSRqbsxCklqw7HHmH5GABn0CLFlFHtXu4iC/Hu+CA8gUgZ4pU3VvjOesm7ZxPTKBkLTt9W45pURipAWyAk5ByEZz9dgL7qD0lCgd/QiqHRkrVGTTyIaZFbph3qYyfA15Jgn+jDl6XHn06MlcH4A1+CFBJ+N7zMdNZCG82V6GcBlrJU0AoAyxHo8RlYEpp3KGOXpS08U3GOZR4Uw65C/7ySo23rPrAWPfBrXgdKdwtgzT3+1D4FCWgnGlbet6d/Qi4XHuhnYcBQz1B9hcJT3no="
  file:
    - build/_output/sort-it-out.wigt
    - build/_output/sort-it-out-build-info.yml
  on:
    tags: true
    repo: ucfopen/sort-it-out-materia-widget
notifications:
  email: false
  slack:
    secure: "WXiL9nqR5wN00bjuMPRfpGHMrJUe25OjbbI68NPUnzG2NJe4w6Z4mCafCwvGIZPcTQr/BYbnMM4OWHQYpiwGKckZBhf5FDK7LFAm5uhl7ja39t8BjQw5dwSqFzGMlXY/yPo3D1yxolr/OyuvapLl8WaP6hcTGhpj8+nGr/mJS1HtC1ZExlSODwz5lvth9l4YWNM27gjiOKBG4SqrBlx7U0v6iIYJRiQU1EIADrV01+ffX+sqf1A80PMcVUcKaE0HWsHE6/Z6P8/6uNhDgdk/Q3UpvIg7vKcJoQOCHefPHlknT7O4A/7D7RG5hxD7eNO74NwZ51Ex016bFMppnvXCJWPjaRzrOsiTiqRdIu9Qqp/hVzWArP4Om3WX3FvaZQqLpavTho8OZa2IbX9hghiwqr/xaA8XG1oz7cKnFNEeiNfWQjaFp6vu9ogu1sESDptO3Kb0h3ofEufRFbIkJ/g84d1BFLbUiZH+WKSdZOvILLs3KYTwaqNGht0d3nbe+4x7k33ReypC7PZc1HYq9JeH0gd3c4RRbKNdXidNS+DIWcR4YVLSo0RWwEFsReMj1BivI6dTNO8ZSj5A8NuQcydg8hyAWdHlEmgYGg8c7pxhwpFmOPrKBT1Tw8GMKjv8SC4Jeu2Ega9duVIwjyZYoTisDLL2O0MfVky0p3IQF9Ic0a8="
